version: "3.9"

services:

  php:
    image: ghcr.io/noc-upaznet/presensi:latest
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    networks:
      - presensi

  nginx:
    image: nginx:latest
    ports:
      - "8083:83"
    depends_on:
      - php
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - presensi

  redis:
    image: redis:alpine
    networks:
      - presensi

networks:
  presensi:

volumes:
  mysql-data:

configs:
  nginx_conf:
    file: docker/nginx/default.conf
