name: Deploy ke Upaznet
on:
  push:
    branches:
      - main
    #tags:
     #- '*'
jobs:
  deploy_tigori:
    name: Deploy ke upaznet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /www/wwwroot/presensi.sandbox.upaz.net.id
            whoami
